// Generated by CoffeeScript 2.7.0
(function() {
  var aString, csOutput, name;

  name = "Henry";

  csOutput = document.getElementById("csOutput");

  csOutput.innerHTML = `Hello ${name}!`;

  aString = "I'm a string";

  if (typeof aString === "string") {
    csOutput.insertAdjacentHTML("beforeend", "<br>aString is a String<br>");
  }

}).call(this);
